// 国家ISO码
export const ISO = ['CL', 'SM', 'GR', 'CA', 'HR', 'JP', 'PL,CZ', 'IT', 'WF', 'SG', 'TF', 'BE', 'IE', 'CH', 'DE', 'MY', 'VA', 'PM', 'LU', 'SI', 'BL', 'CY', 'AT', 'PH', 'NZ', 'EE', 'PL', 'AU', 'PF', 'BO', 'MX', 'GG', 'UY', 'CZ', 'GB', 'DK', 'FI', 'SE', 'GI', 'IM', 'EC', 'RO', 'IS', 'CO', 'LT', 'SK', 'BR', 'AD', 'GE', 'TH', 'ES', 'JE', 'FR', 'Worldwide', 'HU', 'ID', 'MC', 'MT', 'BG', 'PT', 'NO', 'PE', 'NL', 'LI', 'LV'];

// 每个国家支持的本地支付方式
const iso_psp = {
    'GB': ['WeChat', 'Klarna', 'SEPADD', 'PaySafeCard', 'Paysafecash', 'Trustly', 'Alipay+', 'Dragonpay', 'Skrill'],
    'AU': ['Klarna', 'POLi', 'PaySafeCard', 'Alipay+', 'Dragonpay', 'Skrill'],
    'AT': ['Klarna', 'SEPADD', 'Sofort', 'PaySafeCard', 'Paysafecash', 'Alipay+', 'Dragonpay', 'Skrill'],
    'BE': ['Klarna', 'SEPADD', 'Sofort', 'Bancontact', 'PaySafeCard', 'Paysafecash', 'Payconiq', 'Alipay+', 'Dragonpay', 'Skrill'],
    'FI': ['Klarna', 'SEPADD', 'PaySafeCard', 'Trustly', 'Alipay+', 'Dragonpay', 'Skrill'],
    'FR': ['Klarna', 'SEPADD', 'PaySafeCard', 'Paysafecash', 'Alipay+', 'Dragonpay', 'Skrill'],
    'DE': ['Klarna', 'SEPADD', 'Sofort', 'Giropay', 'PaySafeCard', 'Trustly', 'Alipay+', 'Dragonpay', 'Skrill'],
    'GR': ['Klarna', 'SEPADD', 'PaySafeCard', 'Paysafecash', 'Alipay+', 'Dragonpay', 'Skrill'],
    'IE': ['Klarna', 'SEPADD', 'PaySafeCard', 'Paysafecash', 'Alipay+', 'Dragonpay', 'Skrill'],
    'IT': ['Klarna', 'SEPADD', 'MyBank', 'PaySafeCard', 'Paysafecash', 'Alipay+', 'Dragonpay', 'Skrill'],
    'NL': ['Klarna', 'SEPADD', 'Sofort', 'iDEAL', 'PaySafeCard', 'Paysafecash', 'Payconiq', 'Trustly', 'Alipay+', 'Dragonpay', 'Skrill'],
    'PT': ['Klarna', 'SEPADD', 'PaySafeCard', 'Paysafecash', 'Alipay+', 'Dragonpay', 'Skrill'],
    'ES': ['Klarna', 'SEPADD', 'Sofort', 'PaySafeCard', 'Paysafecash', 'Trustly', 'Alipay+', 'Dragonpay', 'Skrill'],
    'CZ': ['Klarna', 'SEPADD', 'PaySafeCard', 'Paysafecash', 'Alipay+', 'Dragonpay', 'Skrill'],
    'DK': ['Klarna', 'SEPADD', 'PaySafeCard', 'Paysafecash', 'Trustly', 'Alipay+', 'Dragonpay', 'Skrill'],
    'NO': ['Klarna', 'SEPADD', 'PaySafeCard', 'Trustly', 'Alipay+', 'Dragonpay', 'Skrill'],
    'PL': ['Klarna', 'Przelewy24', 'SEPADD', 'PaySafeCard', 'Paysafecash', 'Trustly', 'Alipay+', 'Dragonpay', 'Skrill'],
    'SE': ['Klarna', 'SEPADD', 'PaySafeCard', 'Paysafecash', 'Trustly', 'Alipay+', 'Dragonpay', 'Skrill'],
    'CH': ['Klarna', 'SEPADD', 'Sofort', 'PaySafeCard', 'Paysafecash', 'Alipay+', 'Dragonpay', 'Skrill'],
    'BR': ['Boleto', 'BankTransfer', 'Banrisul', 'Bradesco', 'Banco do Brasil', 'Itau', 'MercadoPago', 'PIX', 'Alipay+', 'Dragonpay', 'Skrill'],
    'PH': ['BankTransfer', 'GCash', 'GrabPay', 'PayMaya', 'ELEVEN', 'Alipay+', 'Dragonpay', 'Skrill'],
    'CL': ['Servipag', 'Sencillito', 'Webpay', 'Multicaja', 'Alipay+', 'Dragonpay', 'Skrill'],
    'CO': ['Baloto', 'EFT', 'Efecty', 'Alipay+', 'Dragonpay', 'Skrill'],
    'MX': ['SPEI', 'OXXO', 'OXXOPAY', 'MercadoPago', 'PaySafeCard', 'Alipay+', 'Dragonpay', 'Skrill'],
    'PE': ['PagoEfectivo', 'safetypay-cash', 'safetypay-online', 'PaySafeCard', 'Alipay+', 'Dragonpay', 'Skrill'],
    'PL,CZ': ['PayU', 'Alipay+', 'Dragonpay', 'Skrill'],
    'EC': ['safetypay-cash', 'safetypay-online', 'Alipay+', 'Dragonpay', 'Skrill'],
    'BO': ['Pagosnet', 'Alipay+', 'Dragonpay', 'Skrill'],
    'BG': ['SEPADD', 'PaySafeCard', 'Alipay+', 'Dragonpay', 'Skrill'],
    'HR': ['SEPADD', 'PaySafeCard', 'Paysafecash', 'Alipay+', 'Dragonpay', 'Skrill'],
    'CY': ['SEPADD', 'PaySafeCard', 'Paysafecash', 'Alipay+', 'Dragonpay', 'Skrill'],
    'EE': ['SEPADD', 'PayseraWallet', 'Trustly', 'Alipay+', 'Dragonpay', 'Skrill'],
    'HU': ['SEPADD', 'PaySafeCard', 'Paysafecash', 'Alipay+', 'Dragonpay', 'Skrill'],
    'LV': ['SEPADD', 'PayseraWallet', 'Trustly', 'Alipay+', 'Dragonpay', 'Skrill'],
    'LT': ['SEPADD', 'PayseraWallet', 'LithuanianBanks', 'PaySafeCard', 'Paysafecash', 'Trustly', 'Alipay+', 'Dragonpay', 'Skrill'],
    'LU': ['SEPADD', 'PaySafeCard', 'Paysafecash', 'Payconiq', 'Alipay+', 'Dragonpay', 'Skrill'],
    'MT': ['SEPADD', 'PaySafeCard', 'Paysafecash', 'Alipay+', 'Dragonpay', 'Skrill'],
    'RO': ['SEPADD', 'PaySafeCard', 'Paysafecash', 'Alipay+', 'Dragonpay', 'Skrill'],
    'SK': ['SEPADD', 'PaySafeCard', 'Paysafecash', 'Trustly', 'Alipay+', 'Dragonpay', 'Skrill'],
    'SI': ['SEPADD', 'PaySafeCard', 'Paysafecash', 'Alipay+', 'Dragonpay', 'Skrill'],
    'IS': ['SEPADD', 'Alipay+', 'Dragonpay', 'Skrill'],
    'LI': ['SEPADD', 'PaySafeCard', 'Alipay+', 'Dragonpay', 'Skrill'],
    'AD': ['SEPADD', 'Alipay+', 'Dragonpay', 'Skrill'],
    'SM': ['SEPADD', 'Alipay+', 'Dragonpay', 'Skrill'],
    'MC': ['SEPADD', 'Alipay+', 'Dragonpay', 'Skrill'],
    'VA': ['SEPADD', 'Alipay+', 'Dragonpay', 'Skrill'],
    'PF': ['SEPADD', 'Alipay+', 'Dragonpay', 'Skrill'],
    'TF': ['SEPADD', 'Alipay+', 'Dragonpay', 'Skrill'],
    'GI': ['SEPADD', 'PaySafeCard', 'Alipay+', 'Dragonpay', 'Skrill'],
    'GG': ['SEPADD', 'Alipay+', 'Dragonpay', 'Skrill'],
    'IM': ['SEPADD', 'Alipay+', 'Dragonpay', 'Skrill'],
    'JE': ['SEPADD', 'Alipay+', 'Dragonpay', 'Skrill'],
    'BL': ['SEPADD', 'Alipay+', 'Dragonpay', 'Skrill'],
    'PM': ['SEPADD', 'Alipay+', 'Dragonpay', 'Skrill'],
    'WF': ['SEPADD', 'Alipay+', 'Dragonpay', 'Skrill'],
    'JP': ['Konbini', 'PayEasy', 'Konbini', 'Bank Transfer Japan', 'PayEasy', 'PayPay', 'LINE Pay', 'merPay', 'Rakuten Pay', 'Bit Cash', 'Net Cash', 'Web Money', 'au KDDI', 'SoftBank', 'NTT Docomo', 'Paidy', 'Alipay+', 'Dragonpay', 'Skrill'],
    'ID': ['OVO', 'BNI VA', 'Mandiri ATM', 'Maybank VA', 'Permata VA', 'BRI VA', 'CIMB VA', 'OVO', 'DANA', 'Nobu Bank QRIS', 'AKULAKU', 'ShopeePay', 'Alipay+', 'Dragonpay', 'Skrill'],
    'SG': ['eNETS', 'GrabPay SG', 'Alipay+', 'Dragonpay', 'Skrill'],
    'CA': ['PaySafeCard', 'Paysafecash', 'Alipay+', 'Dragonpay', 'Skrill'],
    'GE': ['PaySafeCard', 'Alipay+', 'Dragonpay', 'Skrill'],
    'NZ': ['PaySafeCard', 'Alipay+', 'Dragonpay', 'Skrill'],
    'UY': ['PaySafeCard', 'Alipay+', 'Dragonpay', 'Skrill'],
    'TH': ['TrueMoney Wallet', 'Rabbit Line Pay', 'PromptPay', 'Krungsri Online', 'Bualuang iBanking', 'Pay with Points - Citi Rewards Points', 'K PLUS', 'Alipay+', 'Dragonpay', 'Skrill'],
    'MY': ['MCASH', 'Touch n Go', 'ShopeePay', 'Boost', 'Alipay+', 'Dragonpay', 'Skrill']
};